spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_edu
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

security:
  jwt:
    token:
      expire-length: 3600000
      secret-key: secret123
